name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: node --version
      - run: npm run format:check
      - run: npm test -- --coverage
      - run: npm --version
        env:
          CI: true
